# Getting base image
FROM nginx:latest
# Running commands on linux machine
RUN apt-get update
RUN apt-get install vim -y

# To generate first docker image you need to run docker build -t {name/imageName} {path}