FROM ubuntu:latest
# When you don't want to accept the command as argument you can use the entrypoint
ENTRYPOINT ["echo", "Hello World" ]
# Can be replaced when calling the image, docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
CMD ["Hello World"]
